// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBscF3MBxv0nuLfs1DvOI1fWBwvz7sxaWY',
    appId: '1:570638068445:web:4c5535a39ba51c961d4934',
    messagingSenderId: '570638068445',
    projectId: 'dinsctor',
    authDomain: 'dinsctor.firebaseapp.com',
    storageBucket: 'dinsctor.firebasestorage.app',
    measurementId: 'G-GT1D95G96J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeH-xjQWJDM42qR2qHiW0bcOqK2ICit7Q',
    appId: '1:570638068445:android:e075f85fd6c06a8f1d4934',
    messagingSenderId: '570638068445',
    projectId: 'dinsctor',
    storageBucket: 'dinsctor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBvXmD11KBcUNi3X81rYVEBjIx-YvkPGc',
    appId: '1:570638068445:ios:cebfed5c87487def1d4934',
    messagingSenderId: '570638068445',
    projectId: 'dinsctor',
    storageBucket: 'dinsctor.firebasestorage.app',
    iosBundleId: 'com.example.studentsChecker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBvXmD11KBcUNi3X81rYVEBjIx-YvkPGc',
    appId: '1:570638068445:ios:cebfed5c87487def1d4934',
    messagingSenderId: '570638068445',
    projectId: 'dinsctor',
    storageBucket: 'dinsctor.firebasestorage.app',
    iosBundleId: 'com.example.studentsChecker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBscF3MBxv0nuLfs1DvOI1fWBwvz7sxaWY',
    appId: '1:570638068445:web:7e9f4d39a5367fff1d4934',
    messagingSenderId: '570638068445',
    projectId: 'dinsctor',
    authDomain: 'dinsctor.firebaseapp.com',
    storageBucket: 'dinsctor.firebasestorage.app',
    measurementId: 'G-0CHT1Y9QJ0',
  );

}